/* ============================================================
   Création de la table DQ_RUN
   ============================================================ */
CREATE TABLE IF NOT EXISTS DB_MEDIATION_BRZ_DEV.SC_CONTROL.DQ_REJECT_EVENT (
    REJECT_ID          VARCHAR(36) DEFAULT UUID_STRING(),
    FEED_ID            VARCHAR(100) NOT NULL,
    RAW_TABLE          VARCHAR(100) NOT NULL,
    CONTROL_ID         VARCHAR(100) NOT NULL,
    RECORD_KEY         NUMBER(38,0) NOT NULL,
    LOAD_TS            TIMESTAMP_NTZ,
    ERROR_CODE         VARCHAR(100),
    ERROR_MESSAGE      VARCHAR(1000),
    ERROR_FIELD        VARCHAR(200),
    ERROR_VALUE        VARCHAR(1000),
    ON_FAILURE_ACTION  VARCHAR(30),
    RAW_RECORD         VARIANT,
    STATUS             VARCHAR(30) DEFAULT 'NEW',
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);




CREATE TABLE IF NOT EXISTS DB_MEDIATION_BRZ_DEV.SC_CONTROL.DQ_WATERMARK (
    FEED_ID        VARCHAR(100) NOT NULL,
    LAST_CHECK_TS  TIMESTAMP_NTZ,
    UPDATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);